apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: backend
          image: virtualthoughts/demo-app:0.0.7
          ports:
            - containerPort: 80