# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Publish

on: [workflow_dispatch]

jobs:

  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Create folder
        run: mkdir ./bin/

      - name: Build
        run: go build -v -o ./bin/example-app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Retrieve latest Docker image version
        id: get_version
        run: |
          echo "::set-output name=image_version::$(curl -s https://hub.docker.com/repository/docker/virtualthoughts/demo-app/tags | jq -r '.[].name' | grep -v latest | sort -V | tail -n 1)"

      - name: Increment version
        id: increment_version
        run: |
          # Increment the retrieved version
          echo "::set-output name=updated_version::$(echo "${{ steps.get_version.outputs.image_version }}" | awk -F. -v OFS=. '{$NF++;print}')"


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: | 
            virtualthoughts/demo-app:${{ steps.increment_version.outputs.updated_version }}
            virtualthoughts/demo-app:latest